version: "3.3"

services:
  mariadb:
    image: mariadb
    container_name: haulingstoredb
    volumes:
      - /var/www/html/haulingstore_com/mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - network
    environment:
      MYSQL_ROOT_PASSWORD: _passW0rd
      MYSQL_DATABASE: wordpress
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  wordpress:
    image: wordpress
    container_name: haulingstorewp
    volumes:
      - /var/www/html/haulingstore_com/wordpress:/var/www/html
    restart: unless-stopped
    networks:
      - network
      - nginx_network
    environment:
      WORDPRESS_DB_HOST: haulingstoredb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: _passW0rd
      WORDPRESS_DB_NAME: wordpress
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  network:
  nginx_network:
    external: true
